<?php
/**
 * @file
 * Code for the Products feature.
 */

include_once 'cb_product.features.inc';


/**
 * Implements hook_update().
 */
function cb_product_pathauto_alias_alter(&$alias, array &$context) {
    if (!empty($context['data']['node'])) {
        $node = $context['data']['node'];

        if ($node->type == 'cb_product') {
            if ($item_id = field_get_items('node', $node, 'field_product_item_id')) {
                $alias .= '-' . $item_id[0]['value'];
            }
        }
    }
}

/**
 * Implements hook_views_pre_view().
 */
function cb_product_views_pre_render(&$view) {
    if ($view->name == 'products') {
        // For all product listing views, set the title to the
        // proper category.
        // The hierarchy is web family > sub-category > category

        if ($view->args[2] == 'all') {
            if ($view->args[1] == 'all' && $view->args[0] != 'all') {
                // Set the category as the title.
                $view->set_title($view->argument['field_product_category_tid']->validated_title);
            }
            else if ($view->args[1] != 'all') {
                // Set the sub category as the title.
                $view->set_title($view->argument['field_prod_sub_category_tid']->validated_title);
            }
            else {
                // Everything must be "all".
                $view->set_title(t('All Products'));
            }
        }
    }
}
